### ISSUE TITLE
Add web responsiveness

### ISSUE THREAD

**Issue by rohanprasadofficial** [rishavanand/github-profilinator#1]
**Is your feature request related to a problem? Please describe.**
 The WebApp is not mobile responsive or small screens.

**Describe the solution you'd like**
The app should be responsive across all the screen sizes.

**Comment by rishavanand** [comment]
Hey @rohanprasadofficial 
Can you check for responsiveness before I merge to master? It is deployed on: [https://dev-profilinator.rishav.dev/](https://dev-profilinator.rishav.dev/)

**Comment by rohanprasadofficial** [comment]
Yeah , Looks better than the previous version @rishavanand

**Comment by rishavanand** [comment]
Alright then, I'll fix the "hello, world" image width and then merge. Thanks.
