### ISSUE TITLE
AWS Skill URL is incorrect

### ISSUE THREAD

**Issue by jordan-mcrae** [rishavanand/github-profilinator#105]
**Describe the bug**
The URL for the AWS skill is incorrect.

**To Reproduce**

Add an AWS skill to your profile, and click on the image. It goes to https://angularjs.org/.

**Expected behavior**

The URL should go to https://aws.amazon.com/

I'll open a PR shortly to fix this!

**Comment by sajjadcodes** [comment]
Hey @jordan-mcrae, 
Is this issue still pending? can assign me. I will fix it.

**Comment by jordan-mcrae** [comment]
> Hey @jordan-mcrae, 
> Is this issue still pending? can assign me. I will fix it.

I have already created the PR and it has been merged into development. It's still pending to be merged into production, #107.

**Comment by rishavanand** [comment]
Just deployed it @jordan-mcrae 
Thanks a lot 🙌

**Comment by sajjadcodes** [comment]
> 

@jordan-mcrae  
That is great. You did a great job 👍.
