### ISSUE TITLE
the position of the dropdown for components like alignment and heading is not the best

### ISSUE THREAD

**Issue by seths10** [rishavanand/github-profilinator#112]
I don't think it is best to place the dropdown icon beneath the main icon.

I suggest you place it beside the component.

**Comment by rishavanand** [comment]
They were on the side previously. There is some UI bug placing it below the main icon which needs to be fixed

**Comment by rishavanand** [comment]
<img width="146" alt="Screenshot 2022-08-28 at 11 22 57 AM" src="https://user-images.githubusercontent.com/11771528/187059795-1a540a86-c53d-44ac-ac6c-ddfea90024f7.png">
