### ISSUE TITLE
Add support me tab 

### ISSUE THREAD

**Issue by rohanprasadofficial** [rishavanand/github-profilinator#20]
**Is your feature request related to a problem? Please describe.**
A "Support Me" tab in the sidebar would be a great option.
**Describe the solution you'd like**
Support me can consist of options like: "Buy Me A Coffee", "Paypal", "Patreon" etc.
**Describe alternatives you've considered**
NA
**Additional context**
An example 
![donate](https://user-images.githubusercontent.com/30728574/90769222-81347480-e30d-11ea-90d3-5b6410065035.png)
*Other options can be added.

**Comment by rohanprasadofficial** [comment]
@rishavanand , I would go for this if possible, I see this as a great option for those who give great opensource projects for the community out of their time.

**Comment by rishavanand** [comment]
Yes @rohanprasadofficial, good point. I'll look into "support me" options along with GitHub sponsors. Thanks.

**Comment by smkamranqadri** [comment]
@rohanprasadofficial have you created buymeacoffee account? if you so please share the link?

**Comment by rohanprasadofficial** [comment]
@smkamranqadri  hey , i am taking something like this , the repo has , there is a "Buy me a coffee" link 
https://github.com/rohanprasadofficial/quotes

**Comment by smkamranqadri** [comment]
In the repo or in the app it self?

also need your username anyhow.

**Comment by smkamranqadri** [comment]
Oh! I missed, that's your repo.

**Comment by smkamranqadri** [comment]
How does it look like?

![Screenshot 2020-10-07 at 7 27 27 PM](https://user-images.githubusercontent.com/13115396/95344491-24981380-08d3-11eb-8a9e-d28b8d02eba8.png)

**Comment by rohanprasadofficial** [comment]
@smkamranqadri we are planning to add it as tab like "Intro" or "My Skill Set" so the people can add Support me options on their readme.
https://github.com/rohanprasadofficial/quotes : This is the link one of my repo.

**Comment by smkamranqadri** [comment]
Okay, well, little bit more info will help understand the task.

**Comment by smkamranqadri** [comment]
Taking this, reviewing the previous code and will do accordingly.

**Comment by smkamranqadri** [comment]
Does it look good?

![Screenshot 2020-10-07 at 9 07 42 PM](https://user-images.githubusercontent.com/13115396/95357321-2668d380-08e1-11eb-8fb4-68d61055bd85.png)

**Comment by smkamranqadri** [comment]
Preview 

![Screenshot 2020-10-07 at 9 59 28 PM](https://user-images.githubusercontent.com/13115396/95363055-6089a380-08e8-11eb-8eac-91a598db3501.png)

**Comment by rishavanand** [comment]
Thank you @smkamranqadri
