### ISSUE TITLE
Dual border for github stats in multi column mode

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#3]
**Is your feature request related to a problem? Please describe.**
Two column mode has it's own border. GitHub Stats Field has its border. So adding stats card to multi column layout leads to 2 borders (1 outer and 1 inner)

**Describe the solution you'd like**
An option to remove borders in GitHub Stats Field.

**Describe alternatives you've considered**
An alternative is using the single column mode so that there are no outer borders.

**Additional context**
Solution is adding &hide_border=true with a toggle option in the GithubStatsField.
Reference: [https://twitter.com/anuraghazru/status/1292685223230976001](https://twitter.com/anuraghazru/status/1292685223230976001)

**Comment by kairavkkp** [comment]
Can I take up the issue?

**Comment by rishavanand** [comment]
Sure, go ahead!
