### ISSUE TITLE
Labels for all field options

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#30]
**Is your feature request related to a problem? Please describe.**
The field options are basically icons and they can be ambiguous at times.

**Describe the solution you'd like**
It will be good to have labels show up on hover for each icon

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kairavkkp** [comment]
Can I take up this issue?

**Comment by rishavanand** [comment]
Sure @kairavkkp !
Tooltip is your way to go.
Thanks.
