### ISSUE TITLE
add accordion option for sections

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#42]
**Is your feature request related to a problem? Please describe.**
Readmes can get really long and all sections might not be equally important. 

**Describe the solution you'd like**
Some sections can be allowed to collapse using accordions.

**Describe alternatives you've considered**
none

**Additional context**
see GitHub stats section in [iampavangandhi's readme](https://github.com/iampavangandhi/iampavangandhi)

**Comment by rishavanand** [comment]
TODO:

- [ ] Add toggle section in `Section Settings` that converts a section into an accordion

**Comment by stspasow** [comment]
Hey, I'm interested in this issue. Could you assign it to me?

**Comment by rishavanand** [comment]
Hey @stspasow, it's all yours.
