### ISSUE TITLE
fields do not show placeholder after textarea conversion

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#45]
**Describe the bug**
During the input to textarea conversion, placeholders got left out.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the social(connect with me) section
4. See missing placeholders on all text areas

**Expected behavior**
Text areas are supposed to show placeholders as there are no labels

**Screenshots**
none

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser chrome

**Comment by thomaslian** [comment]
Hi, I can do this! You just want a placeholder in the TextArea, right? 

Would you prefer this
1. Placeholder:
![image](https://user-images.githubusercontent.com/13934813/95377580-0b975e80-08e3-11eb-8b8a-d6d039abf2e7.png)
Or 
2. Label:
![image](https://user-images.githubusercontent.com/13934813/95377674-32ee2b80-08e3-11eb-9c73-7dc786fbe7db.png)

**Comment by rishavanand** [comment]
Thanks a lot, @thomaslian, your contributions are live on [the dev sudbdomain](https://dev-profilinator.rishav.dev/) and it will be merged into master soon 🎉. Closing this issue.
