### ISSUE TITLE
add search feature for searching skills

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#48]
**Is your feature request related to a problem? Please describe.**
Searching for skill checkboxes is very difficult.

**Describe the solution you'd like**
A search box that can search and show matching skills.

**Describe alternatives you've considered**
none

**Additional context**
Current scenario:
<img width="687" alt="Screenshot 2020-10-08 at 10 14 15 AM" src="https://user-images.githubusercontent.com/11771528/95415869-0839bc80-094f-11eb-81ad-f984e1fade4f.png">

**Comment by alexandramj92** [comment]
I am interested on working on this issue! Can you assign me to it? Thanks!

**Comment by rishavanand** [comment]
Sure @alexandramj92 !

**Comment by AlexPagnotta** [comment]
Hi, I'd like to work on this, it's still open?

**Comment by rishavanand** [comment]
Hi @AlexPagnotta,
Yes, it's still open. Feel free to work on it.

**Comment by rishavanand** [comment]
Resolved in #63.
