### ISSUE TITLE
Convert Input boxes to TextAreas

### ISSUE THREAD

**Issue by rishavanand** [rishavanand/github-profilinator#5]
**Is your feature request related to a problem? Please describe.**
Input boxes are one liners so it becomes very uncovinient while working with sentences/paragraph.

**Describe the solution you'd like**
Converting all inputs to text areas should improve the user's experience

**Describe alternatives you've considered**
An alternative would be that instead of converting all inputs to text areas, there can be an option of one line or multiline in the TextField.

**Additional context**
None

**Comment by lomby92** [comment]
I find this issue searching for `hacktoberfest` tag and i want to contribute but i see that @christeen24 already proposed a solution.

I will write here my opinion about the closed PR: the use of `TextArea` is right but maybe is better with this syntax:
```jsx
<TextArea rows={1} autoSize={true} />
```

With these parameters, the TextArea will be in a single line (as a simple input) and when space is not enough or the 'enter' button is clicked the TextArea will automatically expand

**Comment by rishavanand** [comment]
Hey @lomby92,
I really like your proposed solution, this allows the current look to stay the same but also allows it to change when needed. Since I haven't heard from @christeen24 I can assign you is this issue. Let me know.

**Comment by lomby92** [comment]
I will be happy to provide my PR. Tomorrow morning I will do it 😉
Now it's 17:57 in Italy
