### ISSUE TITLE
Github Readme Activity Graph can be added as a feature

### ISSUE THREAD

**Issue by Ashutosh00710** [rishavanand/github-profilinator#68]
**Describe the solution you'd like**
A dynamically generated [Github Readme Activity Graph](https://github.com/Ashutosh00710/github-readme-activity-graph) can be added as a feature.

I will look like this.

[![Rishav Anand's github activity graph](https://activity-graph.herokuapp.com/graph?username=rishavanand)](https://github.com/ashutosh00710/github-readme-activity-graph)

```md
[![Rishav Anand's github activity graph](https://activity-graph.herokuapp.com/graph?username=rishavanand)](https://github.com/ashutosh00710/github-readme-activity-graph)
```

**Comment by rishavanand** [comment]
Great project @Ashutosh00710 🎉 
This will be an excellent addition.

**Comment by Ashutosh00710** [comment]
Thank You @rishavanand, for considering my project as an addition to yours. ❤
