### ISSUE TITLE
Add Copy Button

### ISSUE THREAD

**Issue by mrjatinchauhan** [rishavanand/github-profilinator#70]
**Is your feature request related to a problem? Please describe.**
A Copy Button beside Generated Markdown. This would allow to copy all in single click over clipboard.

**Describe the solution you'd like**
Something similar to this:
![Github Profilinator - GitHub Profile README Generator](https://user-images.githubusercontent.com/40722235/108218968-40ea6d80-715b-11eb-9467-1add0c231ab6.png)

**Comment by rishavanand** [comment]
Nice little addition. Definitely needed. Thanks!

**Comment by rishavanand** [comment]
Added in this [commit](https://github.com/rishavanand/github-profilinator/commit/69e50ccf908b09518a9a3733316b526f58f3bd15) :) It will be live soon!
