### ISSUE TITLE
Dark Mode Version of the Greeting

### ISSUE THREAD

**Issue by sumeshir26** [rishavanand/github-profilinator#76]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the greeting appears white in dark mode.

**Describe the solution you'd like**
A option to make the greeting's background white.

**Additional context**
![image](https://user-images.githubusercontent.com/68823982/123580118-c384d880-d79e-11eb-94c8-d5061a3f56c9.png)

**Comment by rishavanand** [comment]
Hi @sumeshir26,
The greetings image is merely a sample. When building your readme, you can always replace it with transparent images of your choice.
